### ISSUE TITLE
[Badge] Unread count behavior

### ISSUE THREAD

**Issue by BeatPlus** [protonmail-desktop/application#118]
With https://github.com/BeatPlus/Protonmail/commit/3a62e2c5a71de492b4534484256e4a10ff0f9a25 the badge looks better but some concerns araise. 

From 1 to 4 digits badge:
![Badge](http://i.imgur.com/ZnUrOcz.png)

The badge works well on 2 digits, some 3 digits look good too but >100 gets ugly. We can simply replace with 99+ or something similar so it does not break.

In addition, the badge does not appear when logged in even if you have unread messages. I do like this behavior because it will only appear once a new message comes. Another way is to check for unread messages when the tab loads. Thoughts?

**Comment by kontrollanten** [comment]
"99+" is great!

The reason that the unread emails don't show up immediately is because of Protonmail. When you login to your account the title doesn't display unread emails until you 

1) Get a new email
2) Navigate from Inbox and navigate back to Inbox

From my perspective it's a bug. I think the best would that we (and Protonmail) always display total unread count.

I can contact them regarding this and hear their thoughts.
