### ISSUE TITLE
The password is not remembered when the application is closed.

### ISSUE THREAD

**Issue by Faust30000** [protonmail-desktop/application#149]
The application does not remember the password. If it is closed and restarted, the password must be entered again. This is very inconvenient, especially when the program is in startup.
OS: Linux

**Comment by kontrollanten** [comment]
This application doesn't handle the passwords at all. It's all managed by the ProtonMail web client. Technically it would be possible for us to store the password and auto login upon start, but that could be a security issue since we have to store the password on the computer. I think it's worth a discussion though. In my opinion it's better that people use ProtonMail and store their password on the computer, than if they use Live/Gmail/etc and store their password on the computer.

**Comment by Faust30000** [comment]
I think there should not be security problems. After all, ProtonMail itself supports bridge technology for the integration of mail, for example in Tunberbird. Both the password and the login are stored on the computer. But if you had the opportunity to remember the password in the application, it would be very cool. And then you have to enter a 20-digit password by launching the application.

**Comment by kontrollanten** [comment]
Sounds legit. I'm not that familiar with password storage and encryption though, so I would need to do some research before starting implementing this.

What is the upside if the user anyway has to enter 20-digit password when they're launching the application?

**Comment by Faust30000** [comment]
I have a 20-character password, others probably have much less. Remember this password is very difficult, so I use KeePassXC. So this is the problem: run ProtonMail, run the password manager, copy and paste. It's simpler, of course, if ProtonMail application itself remembered the passwords. I hope you will find a solution to encrypt the storage of the password and login on the computer. Good luck!

**Comment by vladimiry** [comment]
@Faust30000 I'm working on the alternative desktop client also built on top of the Electron. Encrypted settings storage, integration with KeePassXC/Keepass password manager, and some other stuff is already there, it's going to be published on GitHub soon. Though password remembering, as well as the auto-typing the master password from the password manager put you into a danger. Auto-typing password form the password manager is not a secure option because to communicate with a password manager you need the id/key pair, and that pair would be stored unencrypted, so any clever/targeted computer virus could easily read that id/key pair and fetch the master password (or any password if you have allowed access to all the passwords by default in your password manager), decrypt the settings storage and you are exposed. Unfortunately I won't be able to cherry-pick and pull request that features into this app, as it has been built in a quite different way.

**Comment by samiahrocks** [comment]
this actually sounds like a good thing...

**Comment by javaduke** [comment]
It would be really nice if it supported fingerprint authorization as an option.

**Comment by vladimiry** [comment]
There is another app with password remembering support if someone wants to try a beta version https://github.com/vladimiry/protonmail-desktop-app

**Comment by Faust30000** [comment]
**Vladimiry**, will the builds for Ubuntu and its forks be compiled independently?

**Comment by vladimiry** [comment]
@Faust30000 you can modify the electron-builder's list of the linux targets keeping there only needed package formats. It's also should not be a problem to extend npm scripts list assigning building specific packages to a individual scripts, I'd recommend to open an issue with use a case example if there is actual need.

**Comment by jeroen7s** [comment]
you should use the keyring of the computer to store the password, that way it's stored securely
it's usually gnome-keyring on linux, apples keychain on mac and on windows idk what it's called.
bitwardens password manager just released a desktop client based on electron which is open source, and stores the password in the keyring/chain if "remember password" is selected in settings
you might want to check there for inspiration, it's open source

**Comment by vladimiry** [comment]
> that way it's stored securely

System keyring is not a really secure option, any app can read the record, https://github.com/atom/node-keytar/issues/88.

Although if someone needs it, https://github.com/vladimiry/protonmail-desktop-app is alternative of this app with password storing feature using system keyring.

**Comment by chui2ch** [comment]
Is this something that may be added in the future?

**Comment by kontrollanten** [comment]
Yes, it may be added but it's not something prioritized. But if someone wants to create a PR he's welcome =)
